# -*- coding: utf-8 -*-
"""pysparkbasics.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWCIcrE1nS8kH1hcoMxWtW8i-yfJlHbO

# Welcome to Colab!
"""

from pyspark.sql import SparkSession
spark = SparkSession.builder \
  .appName("Demo") \
  .getOrCreate()

data = [
    ("Anil",80,"Maths"),
    ("Sunil",90,"Science"),
    ("Saket",100,"Maths"),
]

columns=["name","marks","subject"]

df=spark.createDataFrame(data,columns)
df.show()

df=df.withColumnRenamed("name","Student_name")
df.show()

from pyspark.sql import SparkSession

spark1 = SparkSession.builder \
  .appName("Employees") \
  .getOrCreate()

data=[
    ("Srinu",50000,'IT'),
    ("Mamatha",60000,'HR'),
    ("Krishna",20000,'IT'),
]

columns=["empname","salary","department"]

df = spark1.createDataFrame(data,columns)
from pyspark.sql.functions import col
df.filter(col("salary")>50000).show()

from pyspark.sql.functions import when
df=df.withColumn("category",when(col("salary")>40000,"High").otherwise("Low"))
df.show()

from pyspark.sql.functions import avg,count
df.groupby("department").agg(
  avg("salary").alias("avg_salary"),
  count("*").alias("total_count")
).show()